with-expecter: True
all: true
filename: "{{.InterfaceName}}.go"
dir: "mocks"
outpkg: "mocks"
log-level: "info"
# tag::packagename[]
packages:
  github.com/steffakasid/go-template:
  # end::packagename[]
    config:
      recursive: True