= Go-Template

image:https://img.shields.io/badge/License-Apache%202.0-blue.svg[link="http://www.apache.org/licenses/LICENSE-2.0"]
image:https://github.com/steffakasid/go-template/actions/workflows/codeql-analysis.yml/badge.svg[link:https://github.com/steffakasid/go-template /actions/workflows/codeql-analysis.yml]
image:https://github.com/steffakasid/go-template/actions/workflows/release.yml/badge.svg[link:https://github.com/steffakasid/go-template/actions/workflows/release.yml]
image:https://github.com/steffakasid/go-template/actions/workflows/go-test.yml/badge.svg[link:https://github.com/steffakasid/go-template/actions/workflows/go-test.yml]

This project is intended to be used as template for new Go projects. The following placeholders must be replaced:

{ .Values.ProjectName }:: The name of the new project.
{ .Values.ShortDescription }:: The short description of that project used in the cobra command.
{ .Values.LongDescription }:: The long description of that project used in the cobra command.

NOTE: Maybe I'll fork `go new` in the future and add some go templating mechanism to add those replacements automatically

Also you should verify the *.mockery.yaml* & *.goreleaser.yaml*:

.mockery.yaml
[source, yaml]
----
include::.mockery.yaml[tags=packagename]
----

.goreleaser.yaml
[source, yaml]
----
include::.goreleaser.yaml[tags=brewrepo]
----


== Usage

Use link:https://go.dev/blog/gonew[] to initialize a new project.

[source, sh]
----
$ go install golang.org/x/tools/cmd/gonew@latest
$ gonew github.com/steffakasid/go-template example.com/myserver
$ cd ./myserver
----

=== Examples

=== Flags
-?, --help:: Print usage information
-v, --version:: Print version information

== Development

=== Generate mock using mockery

In order to test the ec2client I used link:https://github.com/vektra/mockery[mockery] to create the mocks:

.To generate the mocks. Just run:
[source,sh]
----
go generate ./...
----

The mockery configuration is done in:

..mockery.yaml
[source, yaml]
----
include::.mockery.yaml[]
----